/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/TonCWJrBuec
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import { Button } from "@/components/ui/button"
import { CardTitle, CardHeader, CardContent, Card } from "@/components/ui/card"

export function Landing() {
  return (
    <div className="flex flex-col min-h-screen">
      <header className="bg-[#355E3B] text-white py-4 px-6 flex items-center justify-between">
        <Link className="flex items-center gap-2" href="#">
          <FigmaIcon className="w-8 h-8" />
          <span className="text-lg font-bold">Formula 1</span>
        </Link>
        <nav className="hidden md:flex items-center gap-6">
          <Link className="hover:underline" href="#">
            Drivers
          </Link>
          <Link className="hover:underline" href="#">
            Constructors
          </Link>
          <Link className="hover:underline" href="#">
            Races
          </Link>
        </nav>
        <Button className="md:hidden" size="icon" variant="ghost">
          <MenuIcon className="w-6 h-6" />
          <span className="sr-only">Toggle navigation</span>
        </Button>
      </header>
      <div className="flex flex-1">
        <nav className="bg-gray-100 dark:bg-gray-800 p-6 hidden md:block">
          <div className="grid gap-4">
            <Link
              className="flex items-center gap-2 text-gray-500 dark:text-gray-400 hover:text-gray-900 dark:hover:text-gray-50"
              href="#"
            >
              <LayoutDashboardIcon className="w-5 h-5" />
              Dashboard
            </Link>
            <Link
              className="flex items-center gap-2 text-gray-500 dark:text-gray-400 hover:text-gray-900 dark:hover:text-gray-50"
              href="#"
            >
              <TrophyIcon className="w-5 h-5" />
              Standings
            </Link>
            <Link
              className="flex items-center gap-2 text-gray-500 dark:text-gray-400 hover:text-gray-900 dark:hover:text-gray-50"
              href="#"
            >
              <CalendarIcon className="w-5 h-5" />
              Calendar
            </Link>
            <Link
              className="flex items-center gap-2 text-gray-500 dark:text-gray-400 hover:text-gray-900 dark:hover:text-gray-50"
              href="#"
            >
              <SettingsIcon className="w-5 h-5" />
              Settings
            </Link>
          </div>
        </nav>
        <main className="flex-1 p-6">
          <div className="grid gap-6">
            <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-6">
              <Card>
                <CardHeader className="flex items-center justify-between">
                  <CardTitle>Driver Standings</CardTitle>
                  <Link className="text-[#355E3B] dark:text-[#355E3B] hover:underline" href="#">
                    View All
                  </Link>
                </CardHeader>
                <CardContent>
                  <div className="grid gap-2">
                    <div className="flex items-center justify-between">
                      <div className="flex items-center gap-2">
                        <img
                          alt="Max Verstappen"
                          className="rounded-full"
                          height="32"
                          src="/placeholder.svg"
                          style={{
                            aspectRatio: "32/32",
                            objectFit: "cover",
                          }}
                          width="32"
                        />
                        <div>
                          <div className="font-medium">Max Verstappen</div>
                          <div className="text-gray-500 dark:text-gray-400 text-sm">Red Bull</div>
                        </div>
                      </div>
                      <div className="font-medium">234</div>
                    </div>
                    <div className="flex items-center justify-between">
                      <div className="flex items-center gap-2">
                        <img
                          alt="Lewis Hamilton"
                          className="rounded-full"
                          height="32"
                          src="/placeholder.svg"
                          style={{
                            aspectRatio: "32/32",
                            objectFit: "cover",
                          }}
                          width="32"
                        />
                        <div>
                          <div className="font-medium">Lewis Hamilton</div>
                          <div className="text-gray-500 dark:text-gray-400 text-sm">Mercedes</div>
                        </div>
                      </div>
                      <div className="font-medium">189</div>
                    </div>
                    <div className="flex items-center justify-between">
                      <div className="flex items-center gap-2">
                        <img
                          alt="Sergio Perez"
                          className="rounded-full"
                          height="32"
                          src="/placeholder.svg"
                          style={{
                            aspectRatio: "32/32",
                            objectFit: "cover",
                          }}
                          width="32"
                        />
                        <div>
                          <div className="font-medium">Sergio Perez</div>
                          <div className="text-gray-500 dark:text-gray-400 text-sm">Red Bull</div>
                        </div>
                      </div>
                      <div className="font-medium">171</div>
                    </div>
                  </div>
                </CardContent>
              </Card>
              <Card>
                <CardHeader className="flex items-center justify-between">
                  <CardTitle>Constructor Standings</CardTitle>
                  <Link className="text-[#355E3B] dark:text-[#355E3B] hover:underline" href="#">
                    View All
                  </Link>
                </CardHeader>
                <CardContent>
                  <div className="grid gap-2">
                    <div className="flex items-center justify-between">
                      <div className="flex items-center gap-2">
                        <img
                          alt="Red Bull"
                          height="32"
                          src="/placeholder.svg"
                          style={{
                            aspectRatio: "32/32",
                            objectFit: "cover",
                          }}
                          width="32"
                        />
                        <div>
                          <div className="font-medium">Red Bull</div>
                          <div className="text-gray-500 dark:text-gray-400 text-sm">405</div>
                        </div>
                      </div>
                      <div className="font-medium">405</div>
                    </div>
                    <div className="flex items-center justify-between">
                      <div className="flex items-center gap-2">
                        <img
                          alt="Mercedes"
                          height="32"
                          src="/placeholder.svg"
                          style={{
                            aspectRatio: "32/32",
                            objectFit: "cover",
                          }}
                          width="32"
                        />
                        <div>
                          <div className="font-medium">Mercedes</div>
                          <div className="text-gray-500 dark:text-gray-400 text-sm">310</div>
                        </div>
                      </div>
                      <div className="font-medium">310</div>
                    </div>
                    <div className="flex items-center justify-between">
                      <div className="flex items-center gap-2">
                        <img
                          alt="Ferrari"
                          height="32"
                          src="/placeholder.svg"
                          style={{
                            aspectRatio: "32/32",
                            objectFit: "cover",
                          }}
                          width="32"
                        />
                        <div>
                          <div className="font-medium">Ferrari</div>
                          <div className="text-gray-500 dark:text-gray-400 text-sm">274</div>
                        </div>
                      </div>
                      <div className="font-medium">274</div>
                    </div>
                  </div>
                </CardContent>
              </Card>
              <Card>
                <CardHeader className="flex items-center justify-between">
                  <CardTitle>Upcoming Races</CardTitle>
                  <Link className="text-[#355E3B] dark:text-[#355E3B] hover:underline" href="#">
                    View Calendar
                  </Link>
                </CardHeader>
                <CardContent>
                  <div className="grid gap-4">
                    <div className="flex items-center justify-between">
                      <div>
                        <div className="font-medium">Bahrain Grand Prix</div>
                        <div className="text-gray-500 dark:text-gray-400 text-sm">March 5, 2023</div>
                      </div>
                      <Button size="sm" variant="outline">
                        View
                      </Button>
                    </div>
                    <div className="flex items-center justify-between">
                      <div>
                        <div className="font-medium">Saudi Arabian Grand Prix</div>
                        <div className="text-gray-500 dark:text-gray-400 text-sm">March 19, 2023</div>
                      </div>
                      <Button size="sm" variant="outline">
                        View
                      </Button>
                    </div>
                    <div className="flex items-center justify-between">
                      <div>
                        <div className="font-medium">Australian Grand Prix</div>
                        <div className="text-gray-500 dark:text-gray-400 text-sm">April 2, 2023</div>
                      </div>
                      <Button size="sm" variant="outline">
                        View
                      </Button>
                    </div>
                  </div>
                </CardContent>
              </Card>
            </div>
            <div className="grid md:grid-cols-2 gap-6">
              <Card>
                <CardHeader className="flex items-center justify-between">
                  <CardTitle>Latest Race Results</CardTitle>
                  <Link className="text-[#355E3B] dark:text-[#355E3B] hover:underline" href="#">
                    View All
                  </Link>
                </CardHeader>
                <CardContent>
                  <div className="grid gap-2">
                    <div className="flex items-center justify-between">
                      <div className="flex items-center gap-2">
                        <img
                          alt="Max Verstappen"
                          className="rounded-full"
                          height="32"
                          src="/placeholder.svg"
                          style={{
                            aspectRatio: "32/32",
                            objectFit: "cover",
                          }}
                          width="32"
                        />
                        <div>
                          <div className="font-medium">Max Verstappen</div>
                          <div className="text-gray-500 dark:text-gray-400 text-sm">Red Bull</div>
                        </div>
                      </div>
                      <div className="font-medium">1</div>
                    </div>
                    <div className="flex items-center justify-between">
                      <div className="flex items-center gap-2">
                        <img
                          alt="Sergio Perez"
                          className="rounded-full"
                          height="32"
                          src="/placeholder.svg"
                          style={{
                            aspectRatio: "32/32",
                            objectFit: "cover",
                          }}
                          width="32"
                        />
                        <div>
                          <div className="font-medium">Sergio Perez</div>
                          <div className="text-gray-500 dark:text-gray-400 text-sm">Red Bull</div>
                        </div>
                      </div>
                      <div className="font-medium">2</div>
                    </div>
                    <div className="flex items-center justify-between">
                      <div className="flex items-center gap-2">
                        <img
                          alt="Fernando Alonso"
                          className="rounded-full"
                          height="32"
                          src="/placeholder.svg"
                          style={{
                            aspectRatio: "32/32",
                            objectFit: "cover",
                          }}
                          width="32"
                        />
                        <div>
                          <div className="font-medium">Fernando Alonso</div>
                          <div className="text-gray-500 dark:text-gray-400 text-sm">Aston Martin</div>
                        </div>
                      </div>
                      <div className="font-medium">3</div>
                    </div>
                  </div>
                </CardContent>
              </Card>
              <Card>
                <CardHeader className="flex items-center justify-between">
                  <CardTitle>Next Race: Bahrain Grand Prix</CardTitle>
                  <Link className="text-[#355E3B] dark:text-[#355E3B] hover:underline" href="#">
                    View Details
                  </Link>
                </CardHeader>
                <CardContent>
                  <div className="grid gap-4">
                    <div className="flex items-center justify-between">
                      <div>
                        <div className="font-medium">Track Map</div>
                        <div className="text-gray-500 dark:text-gray-400 text-sm">Bahrain International Circuit</div>
                      </div>
                      <img
                        alt="Bahrain Grand Prix Track Map"
                        className="rounded-lg"
                        height={200}
                        src="/placeholder.svg"
                        style={{
                          aspectRatio: "300/200",
                          objectFit: "cover",
                        }}
                        width={300}
                      />
                    </div>
                    <div className="flex items-center justify-between">
                      <div>
                        <div className="font-medium">Race Details</div>
                        <div className="text-gray-500 dark:text-gray-400 text-sm">
                          Date: March 5, 2023
                          <br />
                          Laps: 57
                          <br />
                          Circuit Length: 5.412 km
                        </div>
                      </div>
                      <Button size="sm" variant="outline">
                        View
                      </Button>
                    </div>
                  </div>
                </CardContent>
              </Card>
            </div>
          </div>
        </main>
      </div>
    </div>
  )
}

function CalendarIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M8 2v4" />
      <path d="M16 2v4" />
      <rect width="18" height="18" x="3" y="4" rx="2" />
      <path d="M3 10h18" />
    </svg>
  )
}


function FigmaIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M5 5.5A3.5 3.5 0 0 1 8.5 2H12v7H8.5A3.5 3.5 0 0 1 5 5.5z" />
      <path d="M12 2h3.5a3.5 3.5 0 1 1 0 7H12V2z" />
      <path d="M12 12.5a3.5 3.5 0 1 1 7 0 3.5 3.5 0 1 1-7 0z" />
      <path d="M5 19.5A3.5 3.5 0 0 1 8.5 16H12v3.5a3.5 3.5 0 1 1-7 0z" />
      <path d="M5 12.5A3.5 3.5 0 0 1 8.5 9H12v7H8.5A3.5 3.5 0 0 1 5 12.5z" />
    </svg>
  )
}


function LayoutDashboardIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect width="7" height="9" x="3" y="3" rx="1" />
      <rect width="7" height="5" x="14" y="3" rx="1" />
      <rect width="7" height="9" x="14" y="12" rx="1" />
      <rect width="7" height="5" x="3" y="16" rx="1" />
    </svg>
  )
}


function MenuIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <line x1="4" x2="20" y1="12" y2="12" />
      <line x1="4" x2="20" y1="6" y2="6" />
      <line x1="4" x2="20" y1="18" y2="18" />
    </svg>
  )
}


function SettingsIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M12.22 2h-.44a2 2 0 0 0-2 2v.18a2 2 0 0 1-1 1.73l-.43.25a2 2 0 0 1-2 0l-.15-.08a2 2 0 0 0-2.73.73l-.22.38a2 2 0 0 0 .73 2.73l.15.1a2 2 0 0 1 1 1.72v.51a2 2 0 0 1-1 1.74l-.15.09a2 2 0 0 0-.73 2.73l.22.38a2 2 0 0 0 2.73.73l.15-.08a2 2 0 0 1 2 0l.43.25a2 2 0 0 1 1 1.73V20a2 2 0 0 0 2 2h.44a2 2 0 0 0 2-2v-.18a2 2 0 0 1 1-1.73l.43-.25a2 2 0 0 1 2 0l.15.08a2 2 0 0 0 2.73-.73l.22-.39a2 2 0 0 0-.73-2.73l-.15-.08a2 2 0 0 1-1-1.74v-.5a2 2 0 0 1 1-1.74l.15-.09a2 2 0 0 0 .73-2.73l-.22-.38a2 2 0 0 0-2.73-.73l-.15.08a2 2 0 0 1-2 0l-.43-.25a2 2 0 0 1-1-1.73V4a2 2 0 0 0-2-2z" />
      <circle cx="12" cy="12" r="3" />
    </svg>
  )
}


function TrophyIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M6 9H4.5a2.5 2.5 0 0 1 0-5H6" />
      <path d="M18 9h1.5a2.5 2.5 0 0 0 0-5H18" />
      <path d="M4 22h16" />
      <path d="M10 14.66V17c0 .55-.47.98-.97 1.21C7.85 18.75 7 20.24 7 22" />
      <path d="M14 14.66V17c0 .55.47.98.97 1.21C16.15 18.75 17 20.24 17 22" />
      <path d="M18 2H6v7a6 6 0 0 0 12 0V2Z" />
    </svg>
  )
}
